employees_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from employees_app.employees.views import home

# Mandatory, tuple or list
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='index'),  # localhost:8000 -> home
                  path('employees/', include('employees_app.employees.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees_app/employees/models.py
from django.core import validators
from django.db import models
from django.urls import reverse


class AuditEntity(models.Model):
    created_on = models.DateTimeField(
        auto_now_add=True,
    )
    update_on = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        abstract = True


class Department(AuditEntity):
    name = models.CharField(
        max_length=20,
    )

    def get_absolute_url(self):
        return reverse('department details', kwargs={
            'id': self.id
        })

    def __str__(self):
        return self.name


class Employee(models.Model):
    SOFTWARE_DEVELOPER = 1
    QA_ENGINEER = 2
    DEVOPS_SPECIALIST = 3

    SOFT_UNI = 'SoftUni'
    GOOGLE = 'Google'
    FACEBOOK = 'Facebook'
    AUDI = 'AUDI'
    COMPANIES = (
        SOFT_UNI,
        GOOGLE,
        FACEBOOK,
        AUDI,
    )

    first_name = models.CharField(
        max_length=30,
    )

    last_name = models.CharField(
        max_length=40,
        null=True,
        blank=True,
        default='NO NAME',
    )

    egn = models.CharField(
        max_length=10,
        unique=True,
        verbose_name="EGN",
        validators=(
            validators.MinLengthValidator(10),  # At the end
        )
    )

    job_title = models.IntegerField(
        choices=(
            (SOFTWARE_DEVELOPER, 'Software Developer'),
            (QA_ENGINEER, 'QA Engineer'),
            (DEVOPS_SPECIALIST, 'DevOps Specialist'),
        )
    )

    company = models.CharField(
        max_length=max(len(c) for c in COMPANIES),
        choices=((c, c) for c in COMPANIES),
    )

    # one to many
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
    )

    image = models.ImageField(
        null=True,
        blank=True,
        upload_to='profiles',
    )

    class Meta:
        ordering = ('company', '-first_name',)


class User(models.Model):
    email = models.EmailField()

    # one to one
    employee = models.OneToOneField(
        Employee,
        on_delete=models.CASCADE,
        primary_key=True,
    )


class Project(models.Model):
    name = models.CharField(
        max_length=30,
    )
    dead_line = models.DateField(
        null=True,
        blank=True,
    )

    # Many to many
    employees = models.ManyToManyField(
        to=Employee
    )

templates/templates_examples/index.html
{% extends 'base/base.html' %}
{% load departments_tags %}
{% load int_filters %}
{% load str_filters %}

{% block content %}
    {{ filesize }}
    {{ filesize|filesizeformat }}
    <h1>{{ title }} (Original)</h1>
    <h1>{{ title|lower }} (lower)</h1> {# kind of like map #}
    <h1>{{ title|capfirst }} (capfirst)</h1>
    <h1>{{ title|capitalize }} (capitalize)</h1>
    <h1>{{ title|do_nothing }} (do_nothing)</h1>
    <h1>{{ number_1|increase_by:1000 }}</h1>
    <h1>{{ "123"|increase_by:1000 }}</h1>
    {#<h1>{{ title|increase_by:1000 }}</h1>#}
    <hr/>
    <p>{{ description }} (original)</p>
    <p>{{ description|truncatewords:7 }} (truncatewords:7)</p>
    <p>{{ description|truncatewords:10 }} (truncatewords:10)</p>
    <p>{{ description|truncatechars:7 }} (truncatechars:7)</p>
    <p>{{ description|truncatechars:10 }} (truncatechars:10)</p>
    <div>
        {{ employees }}
    </div>
    <div>
        {{ employees|join:', ' }}
    </div>
    <div>
        {{ department_names|join:', ' }}
    </div>

    <div>
        {% if number_1 < 200 %}
            {{ number_1 }} is less than 200
        {% elif number_1 == 200 %}
            {{ number_1 }} is 200
        {% else %}
            {{ number_1 }} is greater than 200
        {% endif %}
    </div>
    <div>
        {% if number_2 < 200 %}
            {{ number_2 }} is less than 200
        {% elif number_2 == 200 %}
            {{ number_2 }} is 200
        {% else %}
            {{ number_2 }} is greater than 200
        {% endif %}
    </div>
    <div>
        {% if number_3 < 200 %}
            {{ number_3 }} is less than 200
        {% elif number_3 == 200 %}
            {{ number_3 }} is 200
        {% else %}
            {{ number_3 }} is greater than 200
        {% endif %}
    </div>
    {% for number in numbers %}
        <div>
            {{ number }}
        </div>
    {% endfor %}

    {% for number in numbers %}
        <div>
            {% if number < 200 %}
                {{ number }} is less than 200
            {% elif number == 200 %}
                {{ number }} is 200
            {% else %}
                {{ number }} is greater than 200
            {% endif %}
        </div>
    {% endfor %}

    <ul>
        {% for employee in employees %}
            <li>
                {{ employee.first_name }} {{ employee.last_name }}
                (<i>{{ employee.get_job_title_display }}</i>
                in <strong>{{ employee.department.name }}</strong>)
            </li>
        {% endfor %}
    </ul>

    <ul>
        {% for employee in employees %}
            {% ifchanged employee.department.name %}
                <li>---</li>
            {% endifchanged %}
            {% ifchanged employee.first_name %}
                <li>***</li>
            {% endifchanged %}
            <li>
                {{ employee.first_name }} {{ employee.last_name }}
                (<i>{{ employee.get_job_title_display }}</i> in <strong>{{ employee.department.name }}</strong>)
            </li>
        {% endfor %}
    </ul>

    <div>
        {{ csrf_token }}
        {% csrf_token %}
    </div>

    {% departments_list %}

{% endblock %}