employees_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from employees_app.employees.views import home

# Mandatory, tuple or list
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='index'),  # localhost:8000 -> home
                  path('employees/', include('employees_app.employees.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees_app/employees/models.py
from django.core import validators
from django.db import models
from django.urls import reverse


class AuditEntity(models.Model):
    created_on = models.DateTimeField(
        auto_now_add=True,
    )
    update_on = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        abstract = True


class Department(AuditEntity):
    name = models.CharField(
        max_length=20,
    )

    def get_absolute_url(self):
        return reverse('department details', kwargs={
            'id': self.id
        })

    def __str__(self):
        return self.name


class Employee(models.Model):
    SOFTWARE_DEVELOPER = 1
    QA_ENGINEER = 2
    DEVOPS_SPECIALIST = 3

    SOFT_UNI = 'SoftUni'
    GOOGLE = 'Google'
    FACEBOOK = 'Facebook'
    AUDI = 'AUDI'
    COMPANIES = (
        SOFT_UNI,
        GOOGLE,
        FACEBOOK,
        AUDI,
    )

    first_name = models.CharField(
        max_length=30,
    )

    last_name = models.CharField(
        max_length=40,
        null=True,
        blank=True,
        default='NO NAME',
    )

    egn = models.CharField(
        max_length=10,
        unique=True,
        verbose_name="EGN",
        validators=(
            validators.MinLengthValidator(10),  # At the end
        )
    )

    job_title = models.IntegerField(
        choices=(
            (SOFTWARE_DEVELOPER, 'Software Developer'),
            (QA_ENGINEER, 'QA Engineer'),
            (DEVOPS_SPECIALIST, 'DevOps Specialist'),
        )
    )

    company = models.CharField(
        max_length=max(len(c) for c in COMPANIES),
        choices=((c, c) for c in COMPANIES),
    )

    # one to many
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
    )

    image = models.ImageField(
        null=True,
        blank=True,
        upload_to='profiles',
    )

    class Meta:
        ordering = ('company', '-first_name',)


class User(models.Model):
    email = models.EmailField()

    # one to one
    employee = models.OneToOneField(
        Employee,
        on_delete=models.CASCADE,
        primary_key=True,
    )


class Project(models.Model):
    name = models.CharField(
        max_length=30,
    )
    dead_line = models.DateField(
        null=True,
        blank=True,
    )

    # Many to many
    employees = models.ManyToManyField(
        to=Employee
    )

templates/index.html
{% extends 'base/base.html' %}


{# implementing abstract method 'content' #}
{% block content %}
    <h1>The Employees App!</h1>

{% endblock %}

templates/list_departments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>List of departments</h1>
<ul>
    {% for department in departments %}
        <li>
            {{ department.name }}
            <ul>
                {% for employee in department.employee_set.all %}
                    <li>
                        {{ employee.first_name }}
                    </li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
    <hr>
    {% for employee in employees %}
        <li>
            {{ employee.first_name }} ({{ employee.department.name }})
        </li>
    {% endfor %}
</ul>
</body>
</html>